openapi: 3.0.3
info:
    title: API Title
    version: "1.0"
servers:
    - url: https://api.server.test/v1
paths:
    /messages/{id}:
        get:
            tags:
                - Messages
            summary: Retrieve existing message by ID
            parameters:
                - name: id
                  in: path
                  required: true
                  description: The message ID
                  schema:
                      type: integer
            responses:
                "200":
                    description: Message retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Message"
                                
                "400":
                    description: Invalid request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                            examples:
                                default:
                                    $ref: "#/components/examples/InvalidRequest"
                "404":
                    description: Message not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                            examples:
                                default:
                                    $ref: "#/components/examples/MessageNotFound"
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                            examples:
                                default:
                                    $ref: "#/components/examples/InternalServerError"
    /messages/:
        get:
            tags:
                - Messages
            summary: Retrieve all existing messages
            responses:
                "200":
                    description: Messages retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Message"                       
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                            examples:
                                default:
                                    $ref: "#/components/examples/InternalServerError"

components:
    examples:
        InvalidRequest:
            value:
                timestamp: 2026-06-28T14:32:10Z
                status: 400
                error: Invalid request
                message: Invalid request
                path: /messages/123
        MessageNotFound:
            value:
                timestamp: 2026-06-28T14:32:10Z
                status: 404
                error: Not Found
                message: Message not found
                path: /messages/123
        InternalServerError:
            value:
                timestamp: 2026-06-28T14:32:10Z
                status: 500
                error: Internal Server Error
                message: An unexpected error occurred.
                path: /messages/123
    schemas:
        Message:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                sender:
                    type: string
                recipient:
                    type: string
                body:
                    type: string
        ErrorResponse:
            type: object
            properties:
                timestamp:
                    type: string
                    format: date-time
                status:
                    type: integer
                error:
                    type: string
                message:
                    type: string
                path:
                    type: string
